-- Enable RLS on the tables
ALTER TABLE agents ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_telemetry ENABLE ROW LEVEL SECURITY;
ALTER TABLE spans ENABLE ROW LEVEL SECURITY;

-- Agents Policy: Users can only see/modify their own agents
CREATE POLICY tenant_isolation_agents ON agents
    USING (tenant_id = current_setting('app.current_tenant', true)::uuid);

-- Telemetry Policy: Users can only see telemetry generated by their agents
CREATE POLICY tenant_isolation_telemetry ON agent_telemetry
    USING (tenant_id = current_setting('app.current_tenant', true)::uuid);

-- Spans Policy: Users can only see span logs generated by their agents
CREATE POLICY tenant_isolation_spans ON spans
    USING (tenant_id = current_setting('app.current_tenant', true)::uuid);
